INSERT INTO TABLE_PATIENT(NAME, SURNAME, PATRONYMIC, PHONENUMBER)
VALUES ('Дмитрий', 'Лазарев', 'Игоревич', '89376300636');
INSERT INTO TABLE_PATIENT(NAME, SURNAME, PATRONYMIC, PHONENUMBER)
VALUES ('Светлана', 'Васильева', 'Даниловна', '89374589632');
INSERT INTO TABLE_PATIENT(NAME, SURNAME, PATRONYMIC, PHONENUMBER)
VALUES ('Игорь', 'Иванов', 'Петрович', '89378790636');
INSERT INTO TABLE_PATIENT(NAME, SURNAME, PATRONYMIC, PHONENUMBER)
VALUES ('Никита', 'Судаков', 'Иванович', '89371293636');
INSERT INTO TABLE_PATIENT(NAME, SURNAME, PATRONYMIC, PHONENUMBER)
VALUES ('Алексей', 'Зотов', 'Вячеславович', '89376308636');
INSERT INTO TABLE_PATIENT(NAME, SURNAME, PATRONYMIC, PHONENUMBER)
VALUES ('Елена', 'Манакова', 'Сергеевна', '89374800635');
INSERT INTO TABLE_PATIENT(NAME, SURNAME, PATRONYMIC, PHONENUMBER)
VALUES ('Екатерина', 'Самойлова', 'Дмитриевна', '89375129636');
INSERT INTO TABLE_PATIENT(NAME, SURNAME, PATRONYMIC, PHONENUMBER)
VALUES ('Лев', 'Аксенов', 'Николаевич', '89373690136');
INSERT INTO TABLE_PATIENT(NAME, SURNAME, PATRONYMIC, PHONENUMBER)
VALUES ('Светлана', 'Солодова', 'Олеговна', '89372566126');
INSERT INTO TABLE_PATIENT(NAME, SURNAME, PATRONYMIC, PHONENUMBER)
VALUES ('Вячеслав', 'Власов', 'Станович', '89376372536');

INSERT INTO TABLE_DOCTOR(NAME, SURNAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Илья', 'Буяльский', 'Васильевич', 'Хирург');
INSERT INTO TABLE_DOCTOR(NAME, SURNAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Николай', 'Пирогов', 'Иванович', 'Терапевт');
INSERT INTO TABLE_DOCTOR(NAME, SURNAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Сергей', 'Корсаков', 'Сергеевич', 'Психиатр');
INSERT INTO TABLE_DOCTOR(NAME, SURNAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Иван', 'Павлов', 'Петрович', 'Невропатолог');
INSERT INTO TABLE_DOCTOR(NAME, SURNAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Владимир', 'Демихов', 'Петрович', 'Хирург');
INSERT INTO TABLE_DOCTOR(NAME, SURNAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Федор', 'Гааз', 'Петрович', 'Терапевт');
INSERT INTO TABLE_DOCTOR(NAME, SURNAME, PATRONYMIC, SPECIALIZATION)
VALUES ('Григорий', 'Захарьин', 'Антонович', 'Терапевт');

INSERT INTO TABLE_PRESCRIPTION(DESCRIPTION, PATIENTID, DOCTORID, DATACREATION, VALIDITY, PRIORITY)
VALUES ('Принимать Валидол', 5, 2,'2020-08-05','2020-09-05','Нормальный');
INSERT INTO TABLE_PRESCRIPTION(DESCRIPTION, PATIENTID, DOCTORID, DATACREATION, VALIDITY, PRIORITY)
VALUES ('Антидепрессанты', 1, 3,'2020-09-10','2020-11-15','Срочный');
INSERT INTO TABLE_PRESCRIPTION(DESCRIPTION, PATIENTID, DOCTORID, DATACREATION, VALIDITY, PRIORITY)
VALUES ('Физические упражнения', 4, 5,'2020-08-10','2021-08-10','Нормальный');
INSERT INTO TABLE_PRESCRIPTION(DESCRIPTION, PATIENTID, DOCTORID, DATACREATION, VALIDITY, PRIORITY)
VALUES ('Диета', 8, 6,'2020-08-15','2020-09-15','Немедленный');
